# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python actions

on:
  push:
    # push触发
    branches: 
      - master
  schedule:
    # 定时触发
    - cron:  '0 10 * * *'
    # 定时器更改时间
    # https://tool.lu/crontab/
    # https://datetime360.com/cn/utc-cst-china-time/ #UTC时间 国际协调时间+8=北京时间
    # https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#onschedule 官方参考

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install baostock
        pip install akshare
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run main.y
      run:
        python main.py
